spring:
  application:
    name: "${SPRING_APP_NAME:spring-security-explore}"
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:default}"
  security:
    user:
      name: "${SPRING_SECURITY_USER_NAME:admin}"
      password: "${SPRING_SECURITY_USER_PASSWORD:password}"
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://${HOST:localhost}:${PORT:3306}/${SPRING_DATABASE_NAME:sbs}?useSSL=false&serverTimezone=UTC}"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:password}"
    driver-class-name: "${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}"
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20}
      pool-name: ${SPRING_DATASOURCE_HIKARI_POOL_NAME:HikariPool-1}
      auto-commit: ${SPRING_DATASOURCE_HIKARI_AUTO_COMMIT:true}
      transaction-isolation: ${SPRING_DATASOURCE_HIKARI_TRANSACTION_ISOLATION:2}
      register-mbeans: true
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:1800000}
      validation-timeout: ${SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT:5000}
      leak-detection-threshold: ${SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD:0}
  jpa:
    hibernate:
      ddl-auto: "${SPRING_JPA_HIBERNATE_DDL_AUTO:none}"
    show-sql: "${SPRING_JPA_SHOW_SQL:true}"
    properties:
      hibernate:
        dialect: "${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}"
  sql:
    init:
      mode: "${SPRING_SQL_INIT_MODE:NEVER}"
      schema-locations: "${SPRING_SQL_INIT_SCHEMA_LOCATIONS:classpath:script/schema.sql}"

logging:
  pattern:
    console: "${LOGGING_PATTERN_CONSOLE:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){green} : %m%n%wEx}"
  level:
    org:
      springframework:
        security: "${LOGGING_LEVEL_ORG_SPRING_SECURITY:TRACE}"
    org.hibernate.orm.connections.pooling: WARN
